SavingOps/Controllers/FuelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SavingOps.Data;
using SavingOps.Models;

namespace SavingOps.Controllers
{
    [Authorize]
    public class FuelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FuelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Fuels
        public async Task<IActionResult> Index()
        {
              return View();
        }

        // GET: Fuels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Fuel == null)
            {
                return NotFound();
            }

            var fuel = await _context.Fuel
                .FirstOrDefaultAsync(m => m.FuelID == id);
            if (fuel == null)
            {
                return NotFound();
            }

            return View(fuel);
        }

        // GET: Fuels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fuels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FuelID,FuelSubmitted,Cost")] Fuel fuel)
        {
            if (ModelState.IsValid)
            {
                fuel.FuelSubmitted = DateTime.Now;
                _context.Add(fuel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fuel);
        }

        // GET: Fuels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Fuel == null)
            {
                return NotFound();
            }

            var fuel = await _context.Fuel.FindAsync(id);
            if (fuel == null)
            {
                return NotFound();
            }
            return View(fuel);
        }

        // POST: Fuels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FuelID,FuelSubmitted,Cost")] Fuel fuel)
        {
            if (id != fuel.FuelID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fuel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuelExists(fuel.FuelID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fuel);
        }

        // GET: Fuels/Delete/5
        public async Task<IActionResult> Delete()
        {
            var model = _context.Fuel;
            foreach (var i in model)
            {
                _context.Fuel.Remove(i);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Home");
        }

        // POST: Fuels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed()
        {
            var model = _context.Fuel;
            foreach (var i in model)
            {
                _context.Fuel.Remove(i);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Home");
        }

        private bool FuelExists(int id)
        {
          return _context.Fuel.Any(e => e.FuelID == id);
        }

        public IActionResult FuelListPartial()
        {
            return PartialView("_FuelList", _context.Fuel.ToList());
        }
    }
}

SavingOps/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SavingOps.Data;
using SavingOps.Models;
using System.Diagnostics;

namespace SavingOps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated) {
                return RedirectToAction("Dashboard");
            } else
            {
                return View();
            }            
        }

        [Authorize]
        public async Task<IActionResult> Dashboard()
        {
            var model = new ListModel();
            model.AccountList = await _context.AccountSettings.ToListAsync();
            model.BillList = await _context.Bill.ToListAsync();
            model.FuelList = await _context.Fuel.ToListAsync();
            model.RentList = await _context.Rent.ToListAsync();
            model.SavingList = await _context.Saving.ToListAsync();
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SavingOps/Controllers/RentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SavingOps.Data;
using SavingOps.Models;

namespace SavingOps.Controllers
{
    [Authorize]
    public class RentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rents
        public async Task<IActionResult> Index()
        {
              return View();
        }

        // GET: Rents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rent == null)
            {
                return NotFound();
            }

            var rent = await _context.Rent
                .FirstOrDefaultAsync(m => m.RentID == id);
            if (rent == null)
            {
                return NotFound();
            }

            return View(rent);
        }

        // GET: Rents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RentID,DateSubmitted,Cost")] Rent rent)
        {
            if (ModelState.IsValid)
            {
                rent.DateSubmitted = DateTime.Now;
                rent.Cost = _context.AccountSettings.First().RentPrice;
                _context.Add(rent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rent);
        }

        // GET: Rents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Rent == null)
            {
                return NotFound();
            }

            var rent = await _context.Rent.FindAsync(id);
            if (rent == null)
            {
                return NotFound();
            }
            return View(rent);
        }

        // POST: Rents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RentID,DateSubmitted,Cost")] Rent rent)
        {
            if (id != rent.RentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentExists(rent.RentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rent);
        }

        // GET: Rents/Delete/5
        public async Task<IActionResult> Delete()
        {
            var model = _context.Rent;
            foreach (var i in model)
            {
                _context.Rent.Remove(i);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Home");
        }

        // POST: Rents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed()
        {
            var model = _context.Rent;
            foreach (var i in model)
            {
                _context.Rent.Remove(i);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Home");
        }

        private bool RentExists(int id)
        {
          return _context.Rent.Any(e => e.RentID == id);
        }
        public IActionResult RentListPartial()
        {
            return PartialView("_RentList", _context.Rent.ToList());
        }
    }
}

SavingOps/Controllers/SavingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SavingOps.Data;
using SavingOps.Models;

namespace SavingOps.Controllers
{
    [Authorize]
    public class SavingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SavingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Savings
        public async Task<IActionResult> Index()
        {            
            return View();
        }

        // GET: Savings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Saving == null)
            {
                return NotFound();
            }

            var saving = await _context.Saving
                .FirstOrDefaultAsync(m => m.SavingID == id);
            if (saving == null)
            {
                return NotFound();
            }

            return View(saving);
        }

        // GET: Savings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Savings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SavingID,DateSubmitted,Cost")] Saving saving)
        {
            if (ModelState.IsValid)
            {
                saving.DateSubmitted = DateTime.Now;
                _context.Add(saving);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saving);
        }

        // GET: Savings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Saving == null)
            {
                return NotFound();
            }

            var saving = await _context.Saving.FindAsync(id);
            if (saving == null)
            {
                return NotFound();
            }
            return View(saving);
        }

        // POST: Savings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SavingID,DateSubmitted,Cost")] Saving saving)
        {
            if (id != saving.SavingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saving);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SavingExists(saving.SavingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saving);
        }

        // GET: Savings/Delete/5
        public async Task<IActionResult> Delete()
        {
            var model = _context.Saving;
            foreach (var i in model) {
                _context.Saving.Remove(i);
            }
            return RedirectToAction("Dashboard", "Home");
        }

        // POST: Savings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var model = _context.Saving;
            foreach (var i in model)
            {
                _context.Saving.Remove(i);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Home");
        }

        private bool SavingExists(int id)
        {
          return _context.Saving.Any(e => e.SavingID == id);
        }

        public IActionResult SavingListPartial()
        {
            return PartialView("_SavingsList", _context.Saving.ToList());
        }
    }
}

SavingOps/Views/Home/Dashboard.cshtml
@model SavingOps.Models.ListModel;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<div class="dashboard-section">
    <div class="dash-head">
    <div class="head-left">
        <div class="left-row">
            <h1>Dashboard</h1>
            <p>Personal Savings and Updates</p>
        </div>
    </div>
</div>
    <div class="dash-row d-flex justify-content-between mx-auto flex-wrap">
        <a asp-controller="Savings" asp-action="Index">
            <div class="saving-con">
            <h2>Savings Goal</h2>
            <!--Circle Progress-->
                @{
                    if (Model.AccountList.Count == 0)
                    {   
                        <h2>Not Set</h2>
                    } else
                    {
                        double save = 0;
                        foreach (var item in Model.SavingList)
                        {
                            save += item.Cost;
                        }
                        double percent = (save / Model.AccountList[0].SavingsGoal) * 100;
                        <h2>@string.Format("{0:0.00}", percent)%</h2>
                        <h2>@save/@Model.AccountList[0].SavingsGoal</h2>
                    }

                }
        </div>
        </a>
        <a asp-controller="Rents" asp-action="Index">
            <div class="saving-con">
            <h2>Rent Paid</h2>
                @{
                    if(Model.AccountList.Count == 0)
                    {
                        <h2>Not Set</h2>
                        <p>Not Set</p>
                    } else
                    {
                        double rent = 0;
                        foreach (var item in Model.RentList)
                        {
                            rent += item.Cost;
                        }
                        <h2>$@rent</h2>
                        <p>Rent paid by $@Model.AccountList[0].RentPrice per week</p>
                    }
                }
            
        </div>
        </a>

        <a asp-controller="Fuels" asp-action="Index">
            <div class="saving-con">
            <h2>Fuel Paid</h2>
                @{
                    double count = 0;
                    foreach (var item in Model.FuelList)
                    {
                        count += item.Cost;
                    }
                    <h2>$@count</h2>
                }            
            <p>Amount spent towards fuel</p>
        </div>
        </a>
    </div>
    <div class="tabs d-flex justify-content-around mx-auto pb-5">
        <i class="fa-solid fa-house" onclick="openNav('Home')"></i>
        <i class="fa-solid fa-gear" onclick="openNav('Settings')"></i>
        <i class="fa-solid fa-right-from-bracket" onclick="openNav('Logout')"></i>
    </div>
    <hr />
    <div class="nav-link middle-body" id="Home">
            <div class="graph-col d-flex flex-column mx-auto">
                <div class="graph-title">
                <p>Total amount spent Currently</p>
                @{
                    double cost = 0;
                    foreach (var item in Model.RentList)
                    {
                        cost += item.Cost;
                    }
                    foreach (var item in Model.FuelList)
                    {
                        cost += item.Cost;
                    }
                    foreach (var item in Model.SavingList)
                    {
                        cost += item.Cost;
                    }
                    <h2>$@cost</h2>
                }
            </div>
            <div class="graph">
                @{

                }
            </div>           
        </div>     
    </div>

    <div class="nav-link settings"  id="Settings" style="display:none">
        @{
            if (Model.AccountList.Count == 0)
            {
                <div class="zone" id="partialZoneTwo"></div>
            } else
            {
                <div class="zone" id="partialZone"></div>
            }
        }
    </div>

    <div class="nav-link logout-section" id="Logout" style="display:none">
        <h1>Logout</h1>
        <p>Are you sure you want to logout</p>
        <form method="post" asp-controller="Account" asp-action="Logout" >
            <button type="submit" value="Logout">Logout</button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $('#partialZone').load("/AccountSettings/AccountPartial")
        $('#partialZoneTwo').load("/AccountSettings/AddAccountPartial");
    </script>
}

SavingOps/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="splash-screen text-center d-flex flex-column">
    <h1 class="display-1 pt-1 fw-bold">SavingOps</h1>
    <img src="assets/hero-image.png"/>
    <a class="display-6 text-black fw-bold text-decoration-none" asp-area="Identity" asp-page="/Account/Login">Continue...</a>
</div>